export const mockContext = {
  importedColumnHeaders: [
    {
      key: "Manufacturer",
      label: "Manufacturer",
      is_imported: true,
    },
    {
      key: "Name/Description",
      label: "Name/Description",
      is_imported: true,
    },
    {
      key: "Part number",
      label: "Part number",
      is_imported: true,
    },
    {
      key: "Serial",
      label: "Serial",
      is_imported: true,
    },
    {
      key: "DOM",
      label: "DOM",
      is_imported: true,
    },
    {
      key: "Expiry Date",
      label: "Expiry Date",
      is_imported: true,
    },
    {
      key: "Last Inspection Result",
      label: "Last Inspection Result",
      is_imported: true,
    },
    {
      key: "Last Inspection Date",
      label: "Last Inspection Date",
      is_imported: true,
    },
    {
      key: "Previous",
      label: "Previous",
      is_imported: true,
    },
    {
      key: "Standard",
      label: "Standard",
      is_imported: true,
    },
    {
      key: "Comments",
      label: "Comments",
      is_imported: true,
    },
    {
      key: "Group",
      label: "Group",
      is_imported: true,
    },
  ],
  importedFile: {
    path: "Onboarding - testing sheet - Sheet7.csv",
  },
  importedRows: [
    {
      Manufacturer: "Tree Motion",
      "Name/Description": "Harness/Work Positioning",
      "Part number": null,
      Serial: "2021 - 1279",
      DOM: "04/21",
      "Expiry Date": "04/29",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN 358",
      Comments: null,
      Group: "Alfred",
    },
    {
      Manufacturer: "Yale Cordage",
      "Name/Description": "XTC Fire Orange/red/yellow",
      "Part number": "93532V7900005",
      Serial: "Serial no:1438780",
      DOM: "01/2019",
      "Expiry Date": "01/2027",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN1891",
      Comments: "Fit for purpose. No Visible markings",
      Group: "Alfred",
    },
    {
      Manufacturer: "Yale Calamine",
      "Name/Description": "Yale Climbing Rope 11.7mm x 25M",
      "Part number": null,
      Serial: "S/N 20210617 -",
      DOM: "06/2021",
      "Expiry Date": "06/2027",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN 1891",
      Comments: "Good condition",
      Group: "Alfred",
    },
    {
      Manufacturer: "Yale Calamine",
      "Name/Description": "Yale Climbing Rope. Short 11.7mm x 3M",
      "Part number": null,
      Serial: "S/N 20210630 - 1505",
      DOM: "06/2021",
      "Expiry Date": "06/2027",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN 1891",
      Comments: "Good condition",
      Group: "Alfred",
    },
    {
      Manufacturer: "DMM",
      "Name/Description":
        "Carabiner (Green - guessed Ultra O with Silver gate)",
      "Part number": null,
      Serial: "210420208E",
      DOM: "04/2021",
      "Expiry Date": "N/A",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN362",
      Comments: null,
      Group: "Alfred",
    },
    {
      Manufacturer: "DMM",
      "Name/Description": "Carabiner (Blue - guessed Ultra O with Silver gate)",
      "Part number": null,
      Serial: "210420587E",
      DOM: "04/2021",
      "Expiry Date": "N/A",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN362",
      Comments: null,
      Group: "Alfred",
    },
    {
      Manufacturer: "DMM",
      "Name/Description": "Carabiner (Blue - guessed Ultra O with Silver gate)",
      "Part number": null,
      Serial: "210420588E",
      DOM: "04/2021",
      "Expiry Date": "N/A",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN362",
      Comments: null,
      Group: "Alfred",
    },
    {
      Manufacturer: "DMM",
      "Name/Description":
        "Carabiner (Black - Not sure which Style with Orange gate)",
      "Part number": null,
      Serial: "131920714A",
      DOM: 2013,
      "Expiry Date": "N/A",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN362",
      Comments: null,
      Group: "Alfred",
    },
    {
      Manufacturer: "DMM",
      "Name/Description": "Carabiner (Red with Silver gate)",
      "Part number": null,
      Serial: "210412332J",
      DOM: "04/2021",
      "Expiry Date": "N/A",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN362",
      Comments: null,
      Group: "Alfred",
    },
    {
      Manufacturer: "DMM",
      "Name/Description": "Carabiner (Green with Silver gate)",
      "Part number": null,
      Serial: "210420147E",
      DOM: "04/2021",
      "Expiry Date": "N/A",
      "Last Inspection Result": "Pass",
      "Last Inspection Date": "10/07/22",
      Previous: null,
      Standard: "EN362",
      Comments: null,
      Group: "Alfred",
    },
    {
      Manufacturer: "Timbersaws",
      "Name/Description": "Cambium/Friction Saver",
      "Part number": null,
      Serial: 16517,
      DOM: "06/2021",
      "Expiry Date": "Pass",
      "Last Inspection Result": null,
      "Last Inspection Date": null,
      Previous: null,
      Standard: "EN752",
      Comments: "10/07/22",
      Group: "Alfred",
    },
  ],
  mappedColumns: [
    {
      key: "Manufacturer",
      label: "Manufacturer",
      is_imported: true,
    },
    {
      key: "Name/Description",
      label: "Name/Description",
      is_imported: true,
    },
    {
      key: "Part number",
      label: "Part Number",
      is_imported: true,
    },
    {
      key: "Serial",
      label: "Serial Number",
      is_imported: true,
    },
    {
      key: "DOM",
      label: "DOM",
      is_imported: true,
    },
    {
      key: "Expiry Date",
      label: "Expiry Date",
      is_imported: true,
    },
    {
      key: "Last Inspection Result",
      label: "Last Inspection Result",
      is_imported: true,
    },
    {
      key: "Last Inspection Date",
      label: "Last Inspection Date",
      is_imported: true,
    },
    {
      key: "Group",
      label: "Grouping",
      is_imported: true,
    },
  ],
};
